[project]
name = "sample"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "bazis-async-background",
    "bazis-test-utils",
]

[tool.uv.sources]
bazis-async-background = { path = "../", editable = true }

[tool.pytest.ini_options]
django_settings_module = "sample.settings"
